import '../docs/css/style.css'

import { Nothing_You_Could_Do } from 'next/font/google'
import localFont from 'next/font/local'
import Theme from '../theme-provider'
import ClientLayout from './client-layout'

const nycd = Nothing_You_Could_Do({
  subsets: ['latin'],
  variable: '--font-nycd',
  weight: '400',
  display: 'swap'
})

const aspekta = localFont({
  src: [
    {
      path: '../../public/fonts/docs/Aspekta-350.woff2',
      weight: '350',
    },
    {
      path: '../../public/fonts/docs/Aspekta-400.woff2',
      weight: '400',
    },    
    {
      path: '../../public/fonts/docs/Aspekta-500.woff2',
      weight: '500',
    },
    {
      path: '../../public/fonts/docs/Aspekta-650.woff2',
      weight: '650',
    },
  ],
  variable: '--font-aspekta',
  display: 'swap',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="scroll-smooth" suppressHydrationWarning>{/* suppressHydrationWarning: https://github.com/vercel/next.js/issues/44343 */}
      <body className={`${nycd.variable} ${aspekta.variable} font-aspekta antialiased text-slate-800 font-[350] bg-white dark:bg-slate-900 dark:text-slate-200`}>
        <Theme>
          <ClientLayout>
            {children}
          </ClientLayout>
        </Theme>
      </body>
    </html>
  )
}
